# Generated by Django 5.1.6 on 2026-02-25 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bingo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameauditlog',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bingo.game'),
        ),
        migrations.AddField(
            model_name='gameauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='cartela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bingo.cartela'),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='bingo.game'),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameauditlog',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.room'),
        ),
        migrations.AddField(
            model_name='game',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='bingo.room'),
        ),
        migrations.AddField(
            model_name='cartela',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartelas', to='bingo.room'),
        ),
        migrations.AddConstraint(
            model_name='gameplayer',
            constraint=models.UniqueConstraint(fields=('game', 'user'), name='uniq_user_per_game'),
        ),
        migrations.AddConstraint(
            model_name='gameplayer',
            constraint=models.UniqueConstraint(fields=('game', 'cartela'), name='uniq_cartela_per_game'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['room', 'status'], name='bingo_game_room_id_45cab1_idx'),
        ),
    ]
