# Generated by Django 5.1.6 on 2026-02-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(db_index=True, max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("request_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WithdrawRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("telebirr_phone", models.CharField(max_length=32)),
                ("account_holder_name", models.CharField(max_length=128)),
                ("telegram_id_snapshot", models.BigIntegerField(db_index=True)),
                ("request_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("status", models.CharField(choices=[("pending", "pending"), ("paid", "paid"), ("rejected", "rejected")], db_index=True, default="pending", max_length=16)),
                ("admin_note", models.TextField(blank=True, default="")),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("is_suspicious", models.BooleanField(db_index=True, default=False)),
                ("suspicious_reason", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processed_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="processed_withdraw_requests", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="withdraw_requests", to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DepositRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("telebirr_reference", models.CharField(db_index=True, max_length=64, unique=True)),
                ("sender_phone", models.CharField(max_length=32)),
                ("telegram_id_snapshot", models.BigIntegerField(db_index=True)),
                ("request_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("status", models.CharField(choices=[("pending", "pending"), ("approved", "approved"), ("rejected", "rejected")], db_index=True, default="pending", max_length=16)),
                ("admin_note", models.TextField(blank=True, default="")),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processed_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="processed_deposit_requests", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deposit_requests", to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
